kb-jjukkumi/choogoomoneyna_BE

- build.gradle
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/email/controller/EmailAuthController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/email/dto/EmailAuthRequestDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/email/dto/EmailVerifyRequestDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/email/service/EmailAuthService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/email/service/EmailAuthServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/email/util/AuthCodeGenerator.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/email/vo/AuthCodeData.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/JwtAuthenticationEntryPoint.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/JwtAuthenticationFilter.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/JwtProperties.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/JwtTokenProvider.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/RefreshTokenService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/controller/RefreshTokenController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/mapper/RefreshTokenMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/service/RefreshTokenService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/service/RefreshTokenServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/vo/RefreshTokenVO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/config/MailConfig.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/config/MyBatisConfig.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/config/SecurityConfig.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/controller/UserController.java
- src/main/resources/com/choogoomoneyna/refreshToken/mapper/RefreshTokenMapper.xml
이메일 기능 작성했습니다
추후 db 저장 작업이 필요할것 같습니다
템플릿은 아직 안나오는데 제가 적용을 못한걸까요?
> 9 feat 이메일 인증 기능 작성

- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/controller/MatchingMissionResultController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/controller/test/MatchingTestController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/dto/MatchingStatus.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/dto/Response/MatchingMainResponseDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/mapper/MatchingMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/mapper/MatchingMissionResultMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingMissionConverter.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingMissionResultService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingMissionResultServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/vo/MatchingMissionResultVO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/vo/MatchingVO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/vo/RoundInfoVO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mission/dto/response/MissionProgressDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mission/vo/MissionVO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mission/vo/UserMissionVO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/score/vo/UserScoreVO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/vo/MatchedUserVO.java
- src/main/resources/com/choogoomoneyna/matching/mapper/MatchingMapper.xml
- src/main/resources/com/choogoomoneyna/matching/mapper/MatchingMissionResultMapper.xml
- src/main/resources/com/choogoomoneyna/score/mapper/ScoreMapper.xml
- src/main/resources/com/choogoomoneyna/user/mapper/UserMapper.xml
- src/test/java/com/choogoomoneyna/choogoomoneyna_be/matching/controller/MatchingMissionResultControllerTest.java
내 정보와 상대방 정보를 모두 클라이언트에게 전송 하는 기능 추가
---
- Resolved: #14 
---
- 내 정보와 상대방 정보를 클라이언트에게 전송하는 기능 추가
- 위 기능을 클라이언트에게 전송하는 API 추가
- 이에 따른 DTO 변경
---
- [v] 코드가 정상적으로 동작하는지 확인했습니다.
- 
---
> 14 내 정보와 상대방 정보를 모두 클라이언트에게 전송 하는 기능 추가

- src/main/java/com/choogoomoneyna/choogoomoneyna_be/account/codef/controller/CodefController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/account/db/controller/AccountDbController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/CustomUserDetails.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/JwtAuthenticationFilter.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/JwtTokenProvider.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/RefreshTokenService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/controller/test/jwtTestController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/service/RefreshTokenService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/service/RefreshTokenServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/controller/MatchingMissionResultController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/controller/UserController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/service/CustomUserDetailsService.java
매칭 uri 수정
---
- Resolved: #23 
---
- userId 를 토큰에서 추출하도록 설정
- 기존에 jwtTokenProvider 에서 추출하던 코드 수정
---
---
---
> 23 feat 매칭 uri 수정

- build.gradle
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mock/controller/MockController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mock/service/MockService.java
유저 목데이터를 10000건 생성하고 유저,랭킹,점수 테이블에 insert 했습니다.
---
- Resolved: #26 
---
- MockController 생성
- MockService 생성(userMapper, scoreService, rankingService 주입)
---
---
---
> 26 feat mock 데이터 유저 생성

- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/controller/RankingController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/mapper/RankingUserMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/service/RankingUserService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/service/RankingUserServiceImpl.java
- src/main/resources/com/choogoomoneyna/ranking/mapper/RankingMapper.xml
- src/main/resources/com/choogoomoneyna/ranking/mapper/RankingUserMapper.xml
저번 회차 랭킹 가져오기 및 이번 랭킹을 상위 50명까지만 반환 기능으로 변환
---
- Resolved: #37 
---
- 예시: 로그인 UI 개선, API 연동 추가 등
저번 회차 랭킹 가져오기 기능 추가
저번 회차 랭킹 가져오기 api 추가
이번 회차 랭킹을 상위 50명까지 반환으로 수정
이번 회차 랭킹 가져오기 api변경
---
---
---
> 37 feat 저번 회차 랭킹 가져오기 및 이번 랭킹을 상위 50명까지만 반환 기능으로 변환

- src/main/java/com/choogoomoneyna/choogoomoneyna_be/account/codef/controller/CodefController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/account/codef/dto/AccountResponseDto.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/account/codef/dto/TransactionResponseDto.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/account/codef/service/CodefServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/account/codef/vo/AccountVO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/account/db/service/TransactionConverter.java
- src/main/resources/com/choogoomoneyna/account/codef/mapper/AccountMapper.xml
codef 관련 api 자잘자잘한 오류들 수정
---
- Resolved: #35 
---
- 계좌연동 api : 이미 연동된 경우 200, Already added로 응답
- 계좌 한개 업데이트 : api 정상 응답 확인
- 거래내역 : trTime 응답 형식 변환
---
---
---
> 35 feat 계좌 한개 업데이트codef api 구현

- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/service/AuthServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/controller/MatchingMissionResultController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/mapper/RoundInfoMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/RoundInfoService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/RoundInfoServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mock/service/MockService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/controller/RankingController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/mapper/RankingUserMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/service/RankingService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/service/RankingServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/service/RankingUpdateServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/service/RankingUserService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/service/RankingUserServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/vo/RankingUpdateVO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/vo/RankingUserVO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/vo/RankingVO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/score/mapper/ScoreMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/score/service/ScoreService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/score/service/ScoreServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/score/vo/UserScoreVO.java
- src/main/resources/com/choogoomoneyna/matching/mapper/RoundInfoMapper.xml
- src/main/resources/com/choogoomoneyna/ranking/mapper/RankingMapper.xml
- src/main/resources/com/choogoomoneyna/ranking/mapper/RankingUserMapper.xml
- src/main/resources/com/choogoomoneyna/score/mapper/ScoreMapper.xml
- src/test/java/com/choogoomoneyna/choogoomoneyna_be/matching/controller/MatchingMissionResultControllerTest.java
- src/test/java/com/choogoomoneyna/choogoomoneyna_be/ranking/service/RankingServiceImplTest.java
- src/test/java/com/choogoomoneyna/choogoomoneyna_be/user/service/UserServiceImplTest.java
ranking db 수정 및 score db 수정에 따른 코드 수정
---
- Resolved: #42, 
- Resolved: #47
---
ranking db 수정에 따른 rankingVO 변경
rankingVO 변경에 따른 rankingMapper 및 rankingService 변경
rankingService 변경에 따른 rankingController 변경
score db 수정에 따른 scoreVO 변경
scoreVO 변경에 따른 scoreMapper 및 scoreService 변경
scoreService 변경에 따른 scoreController 변경
---
---
---
7
> 42 feat ranking db 수정 및 score db 수정에 따른 코드 수정

- .idea/sqldialects.xml
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/service/AuthServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/mapper/RankingMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/service/RankingServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/report/service/SurveyWeight.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/score/mapper/ScoreMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/score/service/ScoreCalculateService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/score/service/ScoreCalculateServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/score/service/ScoreService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/score/service/ScoreServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/score/vo/UserScoreVO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/controller/UserController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/dto/response/UserMainResponseDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/mapper/UserMainInfoMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/service/UserConverter.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/service/UserMainInfoService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/service/UserMainInfoServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/vo/UserMainInfoVO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/vo/UserVO.java
- src/main/resources/com/choogoomoneyna/ranking/mapper/RankingMapper.xml
- src/main/resources/com/choogoomoneyna/score/mapper/ScoreMapper.xml
- src/main/resources/com/choogoomoneyna/user/mapper/UserMainInfoMapper.xml
- src/main/resources/com/choogoomoneyna/user/mapper/UserMapper.xml
메인화면의 유저 메인 정보 API 추가 api 추가
---
49 feat 메인화면 api 추가
- Resolved: #49
---
- 메인화면의 유저 메인 정보 API 추가
---
---
---
> 49 feat 메인화면의 유저 메인 정보 API 추가 api 추가

- .idea/sqldialects.xml
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/controller/UserController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/dto/response/UserMatchingResultHistoryDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/mapper/UserMatchingResultHistoryMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/service/UserConverter.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/service/UserMatchingResultHistoryService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/service/UserMatchingResultHistoryServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/vo/UserMatchingResultHistoryVO.java
- src/main/resources/com/choogoomoneyna/user/mapper/UserMatchingResultHistoryMapper.xml
유저 메인화면 히스토리 api 작성
---
- Resolved: #55
---
- UserMatchingResultHistoryVO 선언
- UserMatchingResultHistoryDTO 선언
- UserMatchingResultHistoryMapper 구현
- UserMatchingResultHistoryService 구현
- 유저 메인화면 히스토리 api 작성
---
---
---
> 55 feat 유저 메인화면 히스토리 api 작성

- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/vo/RoundInfoVO.java
- src/main/resources/com/choogoomoneyna/matching/mapper/RoundInfoMapper.xml
roundinfo 테이블 수정에 따른 vo 수정
---
- Resolved: #52 
---
- roundinfo 테이블 수정에 따른 vo 수정
- roundInfoMapper.xml 수정
---
---
---
> 52 fix roundinfo 테이블 수정에 따른 vo 수정

- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/vo/UserMatchingHistoryVO.java
- src/main/resources/com/choogoomoneyna/matching/mapper/UserMatchingHistoryMapper.xml
user matching history 테이블 수정에 따른 vo 변경
---
- Resolved: #54 
---
- UserMatchingHistoryVO 의 regDate, updateDate 추가
- UserMatchingHistoryVO 의 id 삭제에 따른 UserMatchingHistoryMapper.xml 수정
---
---
---
> 54 fix user matching history 테이블 수정에 따른 vo 변경

- .idea/sqldialects.xml
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/config/MyBatisConfig.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/controller/SurveyResponseController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/dto/request/SurveyRequestDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/mapper/SurveyResponseMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/service/SurveyCalculatorService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/service/SurveyCalculatorServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/service/SurveyConverter.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/service/SurveyResponseService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/service/SurveyResponseServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/service/SurveyWeightCalculator.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/vo/SurveyResponseVO.java
- src/main/resources/com/choogoomoneyna/survey/mapper/SurveyResponseMapper.xml
- src/main/resources/com/choogoomoneyna/user/mapper/UserMapper.xml
클라이언트로부터 설문조사 결과 받기
---
- Resolved: #33
---
- 주요기능: 설문조사 저장 받기
- 설문조사 받기용 DTO 선언
- 설문조사 저장용 VO 선언
- 설문조사 저장 로직 선언
- 설문조사에서 추구미 추천용 로직 변경
- 추구미 추천 서비스 선언
- 추구미 추천 API 임시 선언
---
---
---
> 33 feat 클라이언트로부터 설문조사 결과 받기

- .idea/sqldialects.xml
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/config/MyBatisConfig.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/vo/MatchingMissionResultVO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/controller/RankingController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/dto/response/RankingChangeResponseDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/dto/response/RankingResponseDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/mapper/RankingUserChangeMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/service/RankingConverter.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/service/RankingUserChangeService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/service/RankingUserChangeServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/vo/RankingUserChangeVO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/vo/RankingUserVO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/controller/SurveyResponseController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/dto/request/SurveyRequestDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/mapper/SurveyResponseMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/service/SurveyCalculatorService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/service/SurveyCalculatorServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/service/SurveyConverter.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/service/SurveyResponseService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/service/SurveyResponseServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/service/SurveyWeightCalculator.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/vo/SurveyResponseVO.java
- src/main/resources/com/choogoomoneyna/matching/mapper/MatchingMissionResultMapper.xml
- src/main/resources/com/choogoomoneyna/ranking/mapper/RankingUserChangeMapper.xml
- src/main/resources/com/choogoomoneyna/ranking/mapper/RankingUserMapper.xml
- src/main/resources/com/choogoomoneyna/survey/mapper/SurveyResponseMapper.xml
- src/main/resources/com/choogoomoneyna/user/mapper/UserMapper.xml
메인화면에 추구미 및 이전랭킹 추가
---
- Resolved: #61 
---
- 주요기능 : 클라이언트에게 추구미 및 이전 랭킹도 함께 보내주기
- vo 와 dto를 분리하여 다르게 전송
---
---
---
> 61 feat ranking 메인화면에 추구미 및 이전랭킹 추가

- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/controller/UserChoogooMiController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/dto/request/UserUpdatedChoogooMiDTO.java
추구미 변경 기능 추가
---
- Resolved: #65
---
- 추구미 변경을 받는 DTO 선언
- 추구미 변경 API 구현
---
---
---
> 65 feat 추구미 변경 기능 추가

- .idea/sqldialects.xml
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingMissionConverter.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mission/dto/response/MissionProgressDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mission/vo/UserMissionVO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/controller/RankingController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/dto/response/RankingHistoryDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/mapper/RankingHistoryMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/service/RankingConverter.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/service/RankingHistoryService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/service/RankingHistoryServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/vo/RankingHistoryVO.java
- src/main/resources/com/choogoomoneyna/matching/mapper/MatchingMissionResultMapper.xml
- src/main/resources/com/choogoomoneyna/ranking/mapper/RankingHistoryMapper.xml
랭킹 히스토리 api 설정하기
---
- Resolved: #64
---
- 랭킹 히스토리 vo, mapper, service 구현
- API 명세서 형식에 맞게 코드 수정
---
---
---
> 64 feat 랭킹 히스토리 api 설정하기

- .idea/sqldialects.xml
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/email/controller/EmailAuthController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/controller/AuthController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingMissionConverter.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mission/dto/response/MissionProgressDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mission/vo/UserMissionVO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/controller/RankingController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/dto/response/RankingHistoryDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/mapper/RankingHistoryMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/service/RankingConverter.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/service/RankingHistoryService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/service/RankingHistoryServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/vo/RankingHistoryVO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/dto/request/UserPasswordResetDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/mapper/UserMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/service/UserService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/service/UserServiceImpl.java
- src/main/resources/com/choogoomoneyna/matching/mapper/MatchingMissionResultMapper.xml
- src/main/resources/com/choogoomoneyna/ranking/mapper/RankingHistoryMapper.xml
- src/main/resources/com/choogoomoneyna/user/mapper/UserMapper.xml
비밀번호 변경 api 작성하기
---
- Resolved: #64
---
- 비밀번호 변경 api 작성하기
---
---
---
> 64 feat 비밀번호 변경 api 작성하기

- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/controller/AuthController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/mapper/UserMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/service/UserService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/service/UserServiceImpl.java
- src/main/resources/com/choogoomoneyna/user/mapper/UserMapper.xml
---
회원 정보 수정에서의 닉네임 중복 체크 기능
- Resolved: #74 
---
- 회원 정보 수정에서의 닉네임 중복 체크 기능
- 회원 정보 수정에서의 닉네임 중복 체크 API 설정
---
---
---
> 74 feat 회원 정보 수정에서의 닉네임 중복 체크 기능

- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/email/controller/EmailAuthController.java
Get 에서 Post로 수정
---
- Get 에서 Post로 수정
---
---
---
> fix: Get 에서 Post로 수정

- .idea/sqldialects.xml
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/report/mapper/ReportMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/report/service/ReportService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/report/service/ReportServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/report/vo/ReportVO.java
- src/main/resources/com/choogoomoneyna/report/mapper/ReportMapper.xml
- src/test/java/com/choogoomoneyna/choogoomoneyna_be/account/db/service/AccountDbServiceTest.java
- src/test/java/com/choogoomoneyna/choogoomoneyna_be/ranking/service/RankingServiceImplTest.java
- src/test/java/com/choogoomoneyna/choogoomoneyna_be/report/service/ReportServiceImplTest.java
---
- Resolved: #85 
---
- 리포트 테이블 만들기
- 리포트 매퍼 CR 만들기
---
---
---
> 85 feat 리포트 테이블 만들기

- src/main/java/com/choogoomoneyna/choogoomoneyna_be/account/db/mapper/AccountMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/account/db/service/AccountDbService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/account/db/service/AccountDbServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/controller/MatchingMissionResultController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/mapper/MatchingMissionResultMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingMissionResultService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingMissionResultServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mission/mapper/MissionMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mission/service/MissionService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mission/service/MissionServiceInterface.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mission/vo/MissionVO.java
- src/main/resources/com/choogoomoneyna/account/codef/mapper/AccountMapper.xml
- src/main/resources/com/choogoomoneyna/matching/mapper/MatchingMissionResultMapper.xml
- src/main/resources/com/choogoomoneyna/mssion/mapper/MissionMapper.xml
미션검증-타입1 CODEF_WEEKLY 미션에 대한 검증 메서드 작성했습니다.
---
- Resolved: #73 
---
- 컨트롤러-missions/validate/1 추가
- 서비스-validateMissionType1 메서드 작성
- 검증로직(CODEF 호출, DB에서 일주일 거래내역 조회, 지출합 계산, 제한금액보다 적으면 성공)
---
---
---
> 73 feat 매칭 미션 수행 검증codef weekly

- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/controller/MatchingMissionResultController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/dto/Request/MatchingMissionQuizUpdateDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/score/service/ScoreCalculateServiceImpl.java
매칭 미션 수행 검증quiz, 점수 저장 문제 해결
---
- Resolved: #92 
---
- 매칭미션결과 서비스에 타입4검증 메서드 추가
- 유저의 퀴즈 획득 점수를 받아오기 위한 dto 추가
- 매칭 종료 시 점수 테이블 업데이트 안되는 문제 해결
---
---
---
> 92 feat 매칭 미션 수행 검증quiz

- src/main/resources/com/choogoomoneyna/account/codef/mapper/AccountMapper.xml
거래내역 항상 최신순으로 정렬해서 응답
---
- Resolved: #94
---
- 거래내역 항상 최신순으로 정렬해서 응답
- api테스트 완료
---
---
---
> feat: 거래내역 항상 최신순으로 정렬해서 응답

- src/main/java/com/choogoomoneyna/choogoomoneyna_be/config/GptConfig.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/config/MyBatisConfig.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/controller/test/MatchingTestController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/enums/ChoogooMiMissionType.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingMissionConverter.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mission/dto/response/MissionProgressDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mission/vo/UserMissionVO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/report/controller/test/ReportTestController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/report/dto/request/GptRequestDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/report/dto/response/GptResponseDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/report/dto/response/OpenAiResponse.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/report/dto/response/ReportResponseDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/report/service/AiClient.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/report/service/ReportControlService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/report/service/ReportControlServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/report/service/ReportConverter.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/report/service/ReportGenerateService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/report/service/ReportGenerateServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/report/service/ReportService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/service/SurveyWeightCalculator.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/enums/ChoogooMi.java
- src/main/resources/com/choogoomoneyna/matching/mapper/MatchingMissionResultMapper.xml
OpenAI api 연결하기
---
- Resolved: #84 
---
- OpenAI api 연결하기
- DB에 저장
- 임시 API 만들기
---
---
---
> 84 feat OpenAI api 연결하기

- build.gradle
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/batch/scheduler/BatchScheduler.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/batch/tasklet/CodefDailyMissionTasklet.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/batch/tasklet/CodefWeeklyMissionTasklet.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/config/BatchConfig.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/config/RootConfig.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/controller/test/MatchingTestController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/mapper/MatchingMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/mapper/MatchingMissionResultMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingMissionResultService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingMissionResultServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mission/mapper/MissionMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mission/service/MissionService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mission/service/MissionServiceImpl.java
- src/main/resources/com/choogoomoneyna/account/codef/mapper/CodefTokenMapper.xml
- src/main/resources/com/choogoomoneyna/matching/mapper/MatchingMapper.xml
- src/main/resources/com/choogoomoneyna/matching/mapper/MatchingMissionResultMapper.xml
- src/main/resources/com/choogoomoneyna/mssion/mapper/MissionMapper.xml
미션 타입 1,2 자동 검증을 위한 배치, 스케줄링 작업했습니다.
---
- Resolved: #104 
---
- 배치설정 추가
- 루트설정에 enableScheduling 애노테이션 추가
- 스케줄링 파일 작성(미션타입1,미션타입2)
- Tasklet 파일 작성(타입 별 각각)
---
---
---
> 104 feat 미션 검증 로직 자동화 작업

- build.gradle
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/account/codef/controller/CodefController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/account/db/controller/AccountDbController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/controller/AuthController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/controller/test/jwtTestController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/service/RefreshTokenServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/util/CustomUserDetails.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/util/JwtAuthenticationEntryPoint.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/util/JwtAuthenticationFilter.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/util/JwtProperties.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/jwt/util/JwtTokenProvider.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/auth/oauth/controller/OAuthController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/config/RootConfig.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/config/SecurityConfig.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/config/ServletConfig.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/config/SwaggerConfig.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/config/WebConfig.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/controller/MatchingController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/controller/MatchingMissionResultController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/ranking/controller/RankingController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/report/controller/ReportController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/survey/controller/SurveyResponseController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/controller/UserChoogooMiController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/controller/UserController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/user/service/CustomUserDetailsService.java
---
- Resolved: #108 
---
- 예시: 로그인 UI 개선, API 연동 추가 등
---
- CompontScan 범위를 줄이기
- config 수정
- swagger 설정하기
---
---
> 108 feat swagger 설정하기

- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/controller/MatchingMissionResultController.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/dto/Request/MatchingMissionTextDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/dto/Response/TextAiResponseDTO.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingMissionResultService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/MatchingMissionResultServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/opneAi/MisisonAiServiceImpl.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/opneAi/MissionAiService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/matching/service/opneAi/OpenAiClient.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mission/mapper/MissionMapper.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mission/service/MissionService.java
- src/main/java/com/choogoomoneyna/choogoomoneyna_be/mission/service/MissionServiceImpl.java
- src/main/resources/com/choogoomoneyna/mssion/mapper/MissionMapper.xml
text input 미션 내용 open ai로 검증, 100점 만점에 70점 이상이어야 성공
---
- Resolved: #117 
---
- 타입3 검증 메서드 추가
- ai request 추가
---
---
---
> 117 feat text input 미션 내용 검증open ai

- src/main/java/com/choogoomoneyna/choogoomoneyna_be/report/service/ReportGenerateServiceImpl.java
추천 추구미 유형 이름만 출력하도록 프롬프트 수정
---
- Resolved: #119 
---
- 지난 번에 카테고리 수정하면서 유형 추천 프롬프트가 설명도 출력하도록 변경되어서
- 이 부분 다시 수정했습니다!
---
---
---
> fix : 추천 추구미 유형 이름만 출력하도록 프롬프트 수정
